# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWfbwz4J44tUeg6PzdRJwJ4oHs1GJjdR
"""

import pandas as pd
df=pd.read_excel("/content/drive/MyDrive/Resume_Screening.xlsx")
def analyze_dataset(df):
  report = {}
  # Store basic information
  report['rows'] = df.shape[0]
  report['columns']= df.shape[1]
  report['column_names'] = df.columns.tolist()
  report['data_types'] = {
    column: str(dtype)
    for column, dtype in df.dtypes.items()
}

  # Store missing values
  report['missing_values'] = df.isnull().sum().to_dict()
  # Calculate missing percentage per column
  report['missing_percentage'] = (df.isnull().sum() / len(df)).to_dict()

  # Store duplicates
  report['duplicate_rows'] = df.duplicated().sum()
  if report['duplicate_rows'] > 0:
    report['duplicate_message'] = 'Recommendation: Consider removing duplicate rows.'

  # Store numerical columns
  report['numerical_columns']=(df.select_dtypes(include="number").columns.tolist())
  # Store categorical columns
  report['categorical_columns']=(df.select_dtypes(include="object").columns.tolist())
  # Store unique values
  report['unique_values'] = df.nunique().to_dict()
  return report

result = analyze_dataset(df)
print(result)

def generate_recommendations(report):
  recommendations = []

  # check duplicates
  # Ensure 'duplicate_rows' key exists in the report
  if 'duplicate_rows' in report:
    if report['duplicate_rows'] > 0:
      recommendations.append('Recommendation: Consider removing duplicate rows.')
    else:
      recommendations.append('No duplicate rows were found.')

  # Add other recommendations based on report content
  # Example: Check for high missing values
  if 'missing_percentage' in report:
    for col, percent in report['missing_percentage'].items():
      if percent > 0: # Example threshold for high missing values
        recommendations.append({
    "column": col,
    "issue": "Missing Values",
    "severity": "Medium",
    "recommendation": "Fill missing values with Mode"
})
  rows = report['rows'] # Re-adding the missing line to define 'rows'

  unique_value=report['unique_values']
  for column, unique_count in unique_value.items():

    if unique_count == rows:
        # ID column recommendation
        recommendations.append({
            "column": column,
            "issue": "Possible ID Column",
            "severity": "Medium",
            "recommendation": "Exclude from model training"
        })
    if unique_count == 1:
        # Constant column recommendation
        pass

  # Recommend encoding for categorical columns
  categorical_columns = report['categorical_columns']

  for column in categorical_columns:
      unique_count = report['unique_values'][column]

      if unique_count == 2:
          recommendations.append({
              "column": column,
              "issue": "Categorical Column",
              "severity": "Medium",
              "recommendation": "Use Label Encoding"
          })
      else:
          recommendations.append({
              "column": column,
              "issue": "Categorical Column",
              "severity": "Medium",
              "recommendation": "Use One-Hot Encoding"
          })



  return recommendations

report = analyze_dataset(df)

recommendations = generate_recommendations(report)

print(recommendations)

from sklearn.preprocessing import LabelEncoder

def apply_recommendations(df, recommendations):

    df = df.copy()

    le = LabelEncoder()

    for rec in recommendations:

        if isinstance(rec, str):
            continue

        column = rec["column"]
        action = rec["recommendation"]

        if action == "Exclude from model training":
            df = df.drop(columns=[column])

        elif action == "Fill missing values with Mode":
            df[column] = df[column].fillna(df[column].mode()[0])

        elif action == "Use Label Encoding":
            df[column] = le.fit_transform(df[column])

        elif action == "Use One-Hot Encoding":
            df = pd.get_dummies(df, columns=[column], drop_first=True)

    return df

report = analyze_dataset(df)

recommendations = generate_recommendations(report)

print(recommendations)

processed_df=apply_recommendations(df,recommendations)
print(processed_df)

processed_df.to_excel("Cleaned_Dataset.xlsx", index=False)
from google.colab import files

files.download("Cleaned_Dataset.xlsx")